### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by renanmav** [LauraBeatris/amazon-next#6]
Maybe you should deploy this on Amazon and put a preview link on the description of the repo. You could use serverless architecture with Lambda. I’d recommend using [`aws-cdk`](https://github.com/aws/aws-cdk).

**Comment by jgcmarins** [comment]
It's deployed here: https://amazon-next.now.sh/

**Comment by LauraBeatris** [comment]
I deployed it with Zeit but some styles from the slick library are not being applied. That's why the home it's really weird right now. 
I gonna fix it!

**Comment by jgcmarins** [comment]
We've already experienced problems deploying Next.js apps into Now, which is weird because both are Zeit products.

**Comment by LauraBeatris** [comment]
I had some problems trying to import the styles of the react-slick lib from node_modules. Now the styles are set via cdn so the product list from home isn't buggy anymore. 

Link for the preview: https://amazon-next.now.sh/
