### ISSUE TITLE
Preview is buggy

### ISSUE THREAD

**Issue by jgcmarins** [LauraBeatris/amazon-next#7]
it looks like that something happened with the production build: https://amazon-next.now.sh/
<img width="1438" alt="Screen Shot 2020-03-04 at 10 22 05" src="https://user-images.githubusercontent.com/5133450/75883659-1eecc380-5e02-11ea-8f74-325ddf3e5f5c.png">

**Comment by LauraBeatris** [comment]
Yes, the styles of the slick library are not being applied in the production build, probably it's because i'm importing from the node_modules

**Comment by LauraBeatris** [comment]
Hi @jgcmarins, 
I had some problems trying to import the styles of the react-slick lib from node_modules. Now the styles are set via cdn so the product list from home isn't buggy anymore.

Link for the preview: https://amazon-next.now.sh/

**Comment by jgcmarins** [comment]
Looks great now \o/
